name: attestation-agent crypto tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'attestation-agent/deps/crypto/**'
      - '.github/workflows/aa_crypto.yml'
  pull_request:
    paths:
      - 'attestation-agent/deps/crypto/**'
      - '.github/workflows/aa_crypto.yml'
  create:

jobs:
  crypto_ci:
    name: Check
    defaults:
      run:
        working-directory: ./attestation-agent
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        suites:
          - rust-crypto
          - openssl

    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust toolchain (stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run rust fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -p crypto -- --check

      - name: Run rust lint check (${{ matrix.suites }})
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # We are getting error in generated code due to derive_partial_eq_without_eq check, so ignore it for now
          args: -p crypto --no-default-features --features ${{ matrix.suites }} -- -D warnings -A clippy::derive_partial_eq_without_eq

      - name: Run cargo test (${{ matrix.suites }})
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p crypto --no-default-features --features ${{ matrix.suites }}
