name: PR Sanity Check
on: [pull_request]

permissions:
  contents: read

jobs:
  commits_check_job:
    permissions:
      pull-requests: read  # for tim-actions/get-pr-commits to get list of commits from the PR
    runs-on: ubuntu-24.04
    name: Commits Check
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
      with:
        egress-policy: audit

    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@198af03565609bb4ed924d1260247b4881f09e7d # master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: DCO Check
      uses: tim-actions/dco@f2279e6e62d5a7d9115b0cb8e837b777b1b02e21 # master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}

