name: check links

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checklinks:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      #  TODO: fix this workflow
      # - name: Restore lychee cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .lycheecache
      #     key: cache-lychee-${{ github.sha }}
      #     restore-keys: cache-lychee-

      # - name: Check links
      #   uses: lycheeverse/lychee-action@v2
      #   with:
      #     args: "--cache --max-cache-age 1d ."
      #     fail: true
